---
authors:
  - "Gaudenz Steinlin <gaudenz.steinlin@cloudscale.ch>"
  - "Denis Krienbühl <denis.krienbuehl@cloudscale.ch>"
  - "René Moser <mail@renemoser.net>"
dependencies: {}
description: 'Ansible Collection for cloudscale.ch'
documentation: ''
homepage: 'https://github.com/cloudscale-ch/ansible-collection-cloudscale'
issues: 'https://github.com/cloudscale-ch/ansible-collection-cloudscale/issues'
license: GPL-3.0-or-later
name: cloud
namespace: cloudscale_ch
readme: README.md
repository: 'https://github.com/cloudscale-ch/ansible-collection-cloudscale'
tags:
  - cloud
  - cloudscale
  - cloudscale_ch
version: 2.0.0
