name: Sanity tests
on:
  schedule:
  - cron: "32 5 * * *"
  pull_request:

jobs:
  sanity:
    name: Sanity tests (${{ matrix.ansible }})
    defaults:
      run:
        working-directory: ansible_collections/cloudscale_ch/cloud
    strategy:
      matrix:
        ansible:
        - stable-2.9
        - stable-2.10
        - stable-2.11
        - stable-2.12
        - stable-2.13
        - stable-2.14
        - devel
    runs-on: ubuntu-20.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        path: ansible_collections/cloudscale_ch/cloud

    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install ansible-base (${{ matrix.ansible }})
      run: pip install https://github.com/ansible/ansible/archive/${{ matrix.ansible }}.tar.gz --disable-pip-version-check

    - name: Run sanity tests
      run: ansible-test sanity --docker -v --color
